# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [metaflow-reprex]

name: metaflow-actions-reprex

jobs:
  metaflow-actions-reprex:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: macos-10.15, r: '3.6'}
          - {os: macos-10.15, r: '4.0'}
          - {os: macos-10.15, r: '4.1'}
          # - {os: macos-10.15, r: 'devel'}
          # - {os: macOS-11,    r: '3.6'}
          - {os: macOS-11,    r: '4.0'}
          - {os: macOS-11,    r: '4.1'}
          # - {os: macOS-11,    r: 'devel'}

    steps:
      - uses: actions/checkout@v2

      - name: Where R you?
        run: |
          which R || echo "No R found"
          ls -ldAT /usr/local/bin/R* \
            || echo "There is no /usr/local/bin/R*"
          ls -ldAT /Library/Frameworks/R.framework/Resources/bin/* \
            || echo "There is no R.framework/Resources/bin"

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - name: Make R and Rscript available on macOS
        if: runner.os == 'macOS'
        run: |
          sudo ln -sf $R_HOME/bin/R /usr/local/bin
          sudo ln -sf $R_HOME/bin/Rscript /usr/local/bin
        env:
          R_HOME: /Library/Frameworks/R.framework/Resources

      - name: Where R you?
        run: |
          which R || echo "No R found"
          ls -ldAT /usr/local/bin/R* \
            || echo "There is no /usr/local/bin/R*"
          ls -ldAT /Library/Frameworks/R.framework/Resources/bin/* \
            || echo "There is no R.framework/Resources/bin"

      - name: Verify R exists
        if: always()
        run: |
          which R && R --vanilla -e '1+1'

      - name: Verify Rscript exists
        if: always()
        run: |
          which Rscript && Rscript -e '1+1'

      - uses: r-lib/actions/setup-r-dependencies@v1
        if: always()
        # just to see some more, incl. sessioninfo

