# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [actions-ubuntu-test]

name: metaflow-actions-reprex

jobs:
  metaflow-actions-reprex:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, pak-${{ matrix.config.pak-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: ubuntu-20.04, r: '3.6'}
          # - {os: ubuntu-20.04, r: '4.0'}
          - {os: ubuntu-20.04, r: '4.1', pak-version: 'stable'}
          - {os: ubuntu-20.04, r: '4.1', pak-version: 'rc'}
          - {os: ubuntu-20.04, r: '4.1', pak-version: 'devel'}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          pak-version: ${{ matrix.config.pak-version }}

